version: '2'

services:
  db:
    image: mysql
    container_name: demo-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql

  web:
    image: nginx:latest
    container_name: demo-web
    restart: always
    depends_on:
      - php
    ports:
      - 80:80
    links:
      - db
    volumes:
      - ./source:/source
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    container_name: demo-php
    restart: always
    build:
      context: ./docker/php/
    volumes:
      - ./source:/source
    env_file:
      - ./env/php.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: demo-phpmyadmin
    links:
      - db
    ports:
      - 81:80
    env_file:
      - ./env/phpmyadmin.env